#include "Engine/Assets/MaterialSerializer.h"
#include "Engine/Assets/AssetRegistry.h"
#include "Engine/Asset/AssetManager.h"
#include "Engine/Renderer/Material.h"
#include "Engine/Renderer/Texture.h"
#include <fstream>
#include <iomanip>
#include <algorithm>
namespace NoJob {
bool MaterialSerializer::Save(const Material&x,const std::filesystem::path&p,const AssetRegistry&){std::ofstream o(p);if(!o)return false;auto&m=const_cast<Material&>(x);auto c=x.GetColor(); auto e=m.EmissiveColor();o<<"NOJOB_MATERIAL 3\nCOLOR "<<c.r<<' '<<c.g<<' '<<c.b<<' '<<c.a<<"\nPBR "<<x.Metallic()<<' '<<x.Roughness()<<' '<<x.AmbientOcclusion()<<' '<<m.NormalStrength()<<"\nEMISSIVE "<<e.r<<' '<<e.g<<' '<<e.b<<' '<<m.EmissiveStrength()<<"\nSURFACE "<<static_cast<int>(x.SurfaceMode())<<' '<<x.AlphaCutoff()<<"\nTEXTURES "<<std::quoted(AssetManager::GetTexturePath(x.GetTexture()).generic_string())<<' '<<std::quoted(AssetManager::GetTexturePath(x.GetNormalTexture()).generic_string())<<' '<<std::quoted(AssetManager::GetTexturePath(x.GetMetallicTexture()).generic_string())<<' '<<std::quoted(AssetManager::GetTexturePath(x.GetRoughnessTexture()).generic_string())<<' '<<std::quoted(AssetManager::GetTexturePath(x.GetAOTexture()).generic_string())<<' '<<std::quoted(AssetManager::GetTexturePath(x.GetEmissiveTexture()).generic_string())<<"\n";return true;}
std::shared_ptr<Material> MaterialSerializer::Load(const std::filesystem::path&p,const std::shared_ptr<Shader>&s,AssetRegistry&){std::ifstream i(p);if(!i)return{};std::string l;std::getline(i,l);if(l.rfind("NOJOB_MATERIAL",0)!=0)return{};auto m=std::make_shared<Material>(s);m->UseTexture()=false;std::string k;while(i>>k){if(k=="COLOR")i>>m->GetColor().r>>m->GetColor().g>>m->GetColor().b>>m->GetColor().a;else if(k=="PBR")i>>m->Metallic()>>m->Roughness()>>m->AmbientOcclusion()>>m->NormalStrength();else if(k=="EMISSIVE")i>>m->EmissiveColor().r>>m->EmissiveColor().g>>m->EmissiveColor().b>>m->EmissiveStrength();else if(k=="SURFACE"){int mode=0;i>>mode>>m->AlphaCutoff();m->SurfaceMode()=static_cast<MaterialSurfaceMode>(std::clamp(mode,0,2));}else if(k=="TEXTURES"){std::string a,n,me,r,ao,e;i>>std::quoted(a)>>std::quoted(n)>>std::quoted(me)>>std::quoted(r)>>std::quoted(ao)>>std::quoted(e);auto L=[](auto&q){return q.empty()?std::shared_ptr<Texture2D>{}:AssetManager::LoadTexture(q);};if(!a.empty()){m->SetTexture(L(a));m->UseTexture()=true;}m->SetNormalTexture(L(n));m->SetMetallicTexture(L(me));m->SetRoughnessTexture(L(r));m->SetAOTexture(L(ao));m->SetEmissiveTexture(L(e));}}return m;}
}