#include "Engine/Assets/PrefabSerializer.h"
#include "Engine/Asset/AssetManager.h"
#include "Engine/Scene/Scene.h"
#include "Engine/Scene/Components.h"
#include "Engine/Renderer/Material.h"
#include "Engine/Renderer/Texture.h"
#include <fstream>
#include <iomanip>
namespace NoJob{
bool PrefabSerializer::Save(Entity e,const std::filesystem::path&p){if(!e)return false;std::filesystem::create_directories(p.parent_path());std::ofstream o(p);if(!o)return false;auto&t=e.GetComponent<TagComponent>();auto&x=e.GetComponent<TransformComponent>();o<<"NOJOB_PREFAB 3\nNAME "<<std::quoted(t.Tag)<<"\nTRANSFORM "<<x.Position.x<<' '<<x.Position.y<<' '<<x.Position.z<<' '<<x.Rotation.x<<' '<<x.Rotation.y<<' '<<x.Rotation.z<<' '<<x.Scale.x<<' '<<x.Scale.y<<' '<<x.Scale.z<<"\n";if(e.HasComponent<MeshComponent>()){auto q=AssetManager::GetMeshPath(e.GetComponent<MeshComponent>().MeshAsset).generic_string();o<<"MESH "<<std::quoted(q.empty()?"CUBE":q)<<"\n";}if(e.HasComponent<MeshRendererComponent>()&&e.GetComponent<MeshRendererComponent>().MaterialAsset){auto m=e.GetComponent<MeshRendererComponent>().MaterialAsset;auto c=m->GetColor();auto ec=m->EmissiveColor();o<<"MATERIAL "<<c.r<<' '<<c.g<<' '<<c.b<<' '<<c.a<<' '<<m->Metallic()<<' '<<m->Roughness()<<' '<<m->AmbientOcclusion()<<' '<<m->NormalStrength()<<' '<<ec.r<<' '<<ec.g<<' '<<ec.b<<' '<<m->EmissiveStrength()<<"\n";o<<"USE_TEXTURE "<<(m->UseTexture()?1:0)<<"\n";o<<"TEXTURES "<<std::quoted(AssetManager::GetTexturePath(m->GetTexture()).generic_string())<<' '<<std::quoted(AssetManager::GetTexturePath(m->GetNormalTexture()).generic_string())<<' '<<std::quoted(AssetManager::GetTexturePath(m->GetMetallicTexture()).generic_string())<<' '<<std::quoted(AssetManager::GetTexturePath(m->GetRoughnessTexture()).generic_string())<<' '<<std::quoted(AssetManager::GetTexturePath(m->GetAOTexture()).generic_string())<<' '<<std::quoted(AssetManager::GetTexturePath(m->GetEmissiveTexture()).generic_string())<<"\n";}return true;}
Entity PrefabSerializer::Instantiate(Scene&s,const std::filesystem::path&p,const std::shared_ptr<Mesh>&fb,const std::shared_ptr<Material>&base){std::ifstream i(p);if(!i)return{};std::string h;i>>h;if(h!="NOJOB_PREFAB")return{};int v;i>>v;std::string k,name="Prefab",mp,a,n,me,r,aop,em;glm::vec3 pos{},rot{},sc{1},ec{};glm::vec4 col{1};float mt=0,ro=.5f,ao=1,ns=1,es=0;bool hm=false;bool useTexture=false;while(i>>k){if(k=="NAME")i>>std::quoted(name);else if(k=="TRANSFORM")i>>pos.x>>pos.y>>pos.z>>rot.x>>rot.y>>rot.z>>sc.x>>sc.y>>sc.z;else if(k=="MESH")i>>std::quoted(mp);else if(k=="MATERIAL"){i>>col.r>>col.g>>col.b>>col.a>>mt>>ro>>ao>>ns>>ec.r>>ec.g>>ec.b>>es;hm=true;}else if(k=="USE_TEXTURE"){int enabled=0;i>>enabled;useTexture=enabled!=0;}else if(k=="TEXTURES")i>>std::quoted(a)>>std::quoted(n)>>std::quoted(me)>>std::quoted(r)>>std::quoted(aop)>>std::quoted(em);}auto e=s.CreateEntity(name);auto&tr=e.GetComponent<TransformComponent>();tr.Position=pos;tr.Rotation=rot;tr.Scale=sc;if(!mp.empty()){try{e.AddComponent<MeshComponent>(mp=="CUBE"?fb:AssetManager::LoadMesh(mp));}catch(...){e.AddComponent<MeshComponent>(fb);}}if(hm){auto m=std::make_shared<Material>(*base);m->GetColor()=col;m->Metallic()=mt;m->Roughness()=ro;m->AmbientOcclusion()=ao;m->NormalStrength()=ns;m->EmissiveColor()=ec;m->EmissiveStrength()=es;m->UseTexture()=false;auto L=[](auto&q){return q.empty()?std::shared_ptr<Texture2D>{}:AssetManager::LoadTexture(q);};if(!a.empty()){m->SetTexture(L(a));if(v<3)useTexture=true;}m->UseTexture()=useTexture&&(m->GetTexture()!=nullptr);m->SetNormalTexture(L(n));m->SetMetallicTexture(L(me));m->SetRoughnessTexture(L(r));m->SetAOTexture(L(aop));m->SetEmissiveTexture(L(em));e.AddComponent<MeshRendererComponent>(m);}return e;}
}